FROM fiadliel/java8-jre
COPY paymentgateway-api2.jar /paymentgateway/
COPY lib /paymentgateway/lib/
COPY db /paymentgateway/db/
CMD [ "java", "-jar", "/paymentgateway/paymentgateway-api2.jar" ]
EXPOSE 5552
